# Generated by Django 6.0.2 on 2026-03-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_curta', models.TextField(max_length=150)),
                ('descricao_longa', models.TextField(max_length=300)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produto/produto_img/%y/03')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('preco_marketing', models.FloatField()),
                ('preco_marketing_promocional', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('V', 'Variação'), ('S', 'Simples')], default='V', max_length=1)),
            ],
        ),
    ]
