# Generated by Django 6.0.2 on 2026-03-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='Produto sem nome', max_length=80),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produto/produto_imagens/%y/%m'),
        ),
    ]
